image:
  file: .gitpod.dockerfile
ports:
    - port: 3000
      onOpen: open-preview
tasks:
    - init: >
        pip install pipenv==2022.1.8;
        pipenv install;
    - command: python3 welcome.py
